[build]
    command = "pnpm run build"
    publish = "dist"

[build.environment]
    NODE_VERSION = "26.3.0"

[[redirects]]
    from = "/dof/*"
    to = "https://depth-of-field.netlify.app/:splat"
    status = 200
    force = false

[[redirects]]
    from = "/travel/paris/"
    to = "/travel/france/"
    status = 301
    force = false

[[redirects]]
    from = "/travel/peru-argentina/"
    to = "/travel/"
    status = 301
    force = false

[[redirects]]
    from = "/travel/argentina/"
    to = "/travel/uruguay/"
    status = 307
    force = false

[[redirects]]
    from = "/travel/britain-benelux/"
    to = "/travel/"
    status = 301
    force = false

[[redirects]]
    from = "/trip-planner/*"
    to = "https://ephemeral-lokum-dab4cc.netlify.app/trip-planner/:splat"
    status = 200
    force = false
