[[redirects]]
    from = "/blog/*"
    to = "https://patik-blog.netlify.app/:splat"
    status = 200
    force = false

[[redirects]]
    from = "/dof/*"
    to = "https://depth-of-field.netlify.app/:splat"
    status = 200
    force = false

[[redirects]]
    from = "/travel/paris/"
    to = "/travel/france/"
    status = 301
    force = false

[[redirects]]
    from = "/travel/peru-argentina/"
    to = "/travel/"
    status = 301
    force = false

[[redirects]]
    from = "/travel/britain-benelux/"
    to = "/travel/"
    status = 301
    force = false
